### ISSUE TITLE
NtlmTransport fails on header "Www-Authenticate" with multiple options

### ISSUE THREAD

**Issue by mazeForGit** [vadimi/go-http-ntlm#10]
If the server sends multiple options for authentication the current implementation fails with with error = illegal base64 data at input byte 8. The reason is that the http.headers.Get() returns string but is []string in this case.

My changes to "ntlmtransport.go" address this problem in a way to read the header "Www-Authenticate" as []string and extracts the "NTLM" string.

		//
		// bug-fix ... start
		// original implemementation
		// fails if multiple options are available with error = illegal base64 data at input byte 8
                //
		// 0 Negotiate
		// 1 NTLM TlRMTVNTUAACAAAAEAAQADgAAAAFgoniOOV2GGY5Y1AAAAAAAAAAAIQAhABIAAAABgOAJQAAAA9EAEUAVgBXAEEARwAwADAAAgAQAEQARQBWAFcAQQBHADAAMAABABgAQwBBAFIATQBCAEUAUwAwADAAMAA1ADUABAAMAHYAdwAuAHYAdwBnAAMAJgBDAEEAUgBNAEIARQBTADAAMAAwADUANQAuAHYAdwAuAHYAdwBnAAUABgB2AHcAZwAHAAgAIMKfkb561gEAAAAA
		// 2 Basic realm="VisualSVN Server"
		//
		//
		// resp.Header.Get() returns string but it is []string in this particular case
		// 
		var ntlmChallengeHeader string
		var stringArray []string
		for key, element := range resp.Header {
				// fmt.Println("Key:", key, "=>", "Element:", element)
				// fmt.Println(reflect.TypeOf(element))
				if key == "Www-Authenticate" {
					//fmt.Println("reflect type of element = ")
					stringArray = element
				}
			}

		for _, s := range stringArray {
		//for i, s := range stringArray {
			//fmt.Println(i, s)
			if strings.HasPrefix(s, "NTLM") {
				ntlmChallengeHeader = s
			}
		}
		fmt.Println("ntlmChallengeHeader = " + ntlmChallengeHeader)

		//
		// bug-fix ... end
		//
	
		//
		// original implemementation .. start
		//
		
		// retrieve Www-Authenticate header from response
		//ntlmChallengeHeader := resp.Header.Get("WWW-Authenticate")
		//if ntlmChallengeHeader == "" {
		//	return nil, errors.New("Wrong WWW-Authenticate header")
		//}

		//
		// original implemementation .. end
		//

**Comment by vadimi** [comment]
@mazeForGit thanks for reporting and the analysis, I'll try to come up with a fix some time this week, unless you want to submit a PR.

**Comment by mazeForGit** [comment]
Thanks for the quick response.
I tested your solution and it works fine.
Best Regards!

**Comment by vadimi** [comment]
@mazeForGit thanks for testing!
