### ISSUE TITLE
Not sure if negotiate() is correct?

### ISSUE THREAD

**Issue by kmansoft** [vadimi/go-http-ntlm#13]
Hi,

I've compared your negotiate() function with Apache's NTLM implementation:

https://github.com/apache/httpcomponents-client/blob/22cf9671b139be6b49fceda7f43b2a9476fbd67c/httpclient5/src/main/java/org/apache/hc/client5/http/impl/auth/NTLMEngineImpl.java#L1346

Differences:

- Apache's negotiate header length is 40 bytes, not 44 as yours is
- Apache sets hostname offset to 40 (just beyond the end of the structure), even when there is no hostname present
- Apache sends Windows version (imitating Windows 7, I beleive)
- Apache sends NTLM version

Corrected code, if I may:

```go
// generates NTLM Negotiate type-1 message
// for details see http://www.innovation.ch/personal/ronald/ntlm.html
func negotiate() []byte {
	/* original code:
	ret := make([]byte, 44)
	*/
	// Change by kman based on NTLMEngineImpl from Apache
	ret := make([]byte, 40)

	flags := negotiateAlwaysSign | negotiateExtendedSessionSecurity | negotiateKeyExch | negotiate128 | negotiate56 | negotiateNTLM | requestTarget | negotiateOEM | negotiateUnicode

	copy(ret, []byte("NTLMSSP\x00")) // protocol
	put32(ret[8:], 1)                // type
	put32(ret[12:], uint32(flags))   // flags
	put16(ret[16:], 0)               // NT domain name length
	put16(ret[18:], 0)               // NT domain name max length
	put32(ret[20:], 0)               // NT domain name offset
	put16(ret[24:], 0)               // local workstation name length
	put16(ret[26:], 0)               // local workstation name max length

	/* original code:
	put32(ret[28:], 0)               // local workstation name offset
	put16(ret[32:], 0)               // unknown name length
	put16(ret[34:], 0)               // ...
	put16(ret[36:], 0x30)            // unknown offset
	put16(ret[38:], 0)               // unknown name length
	put16(ret[40:], 0)               // ...
	put16(ret[42:], 0x30)            // unknown offset
	*/

	// Change by kman based on NTLMEngineImpl from Apache
	put32(ret[28:], 32 + 8)		// local workstation name offset
	put16(ret[32:], 0x0105)		// windows version
	put32(ret[34:], 2600)			// windows build
	put16(ret[38:], 0x0f00)		// NTLM revision

	return ret
}
```

**Comment by vadimi** [comment]
hi @kmansoft, yes, you're right, it should be 40 bytes, not 44. The "Version" field should be 8 bytes, not 12. But since it never sets the version (also the version is used for debugging purposes only) then it wasn't really an issue and never broke anything I used this library for.

Does it break anything for you?

Also in order to send the version it's necessary to enable NTLMSSP_NEGOTIATE_VERSION flag according to https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-nlmp/b34032e5-3aae-4bc6-84c3-c6d80eadf7f2

**Comment by kmansoft** [comment]
@vadimi thank you for docs link.

About "break anything" - _maybe_. I'm currently working with a user who used to get http 401 unauthorized, now he's getting a different error :) This is a mail app connecting to MS Exchange.

**Comment by vadimi** [comment]
alright @kmansoft, could you give this branch a try? https://github.com/vadimi/go-http-ntlm/tree/negotiate-version-flag
