### ISSUE TITLE
Build error on 32-bit systems because of int overflow

### ISSUE THREAD

**Issue by keachi** [vadimi/go-http-ntlm#16]
Thank you for this great library, it makes using NTLM authentication much easier!
While building binaries with this library for 32-bit systems, the build fails because of an int overflow.
```
$ GOOS=linux GOARCH=386 go build .
# github.com/vadimi/go-http-ntlm/v2
/go/pkg/mod/github.com/vadimi/go-http-ntlm/v2@v2.3.0/negotiator.go:36:8: constant 3792208391 overflows int
```
`GOARCH=arm` is affected too by this bug. Is it possible to increase the constant to an int64?

**Comment by vadimi** [comment]
hi @keachi, yes, absolutely. Could you give this branch a try? https://github.com/vadimi/go-http-ntlm/tree/fix-int-overflow

I think `uint32` should help as well
