### ISSUE TITLE
 resp.Header.Values undefined

### ISSUE THREAD

**Issue by diekloope** [vadimi/go-http-ntlm#18]
Hi, I tried to run the example and get following error message:
#github.com/vadimi/go-http-ntlm/v2
..\..\..\pkg\mod\github.com\vadimi\go-http-ntlm\v2@v2.3.1\ntlmtransport.go:55:29: resp.Header.Values undefined (type http.Header has no field or method Values)

**Comment by vadimi** [comment]
hello @diekloope, which go version do you use? `.Values` is available since go 1.14: https://golang.org/doc/go1.14#net/http

**Comment by diekloope** [comment]
Hello @vadimi, thanks. I have updated my go version. But now ig get the error message;
`TLSClientConfig: &tls.Config{}` --> undefined: tls go

**Comment by vadimi** [comment]
@diekloope could you show the full source code including the imports?

**Comment by vadimi** [comment]
please reopen if you feel there is an issue with the library
