### ISSUE TITLE
Length validation in ParseChallengeMessage

### ISSUE THREAD

**Issue by kmansoft** [vadimi/go-http-ntlm#19]
Hello,

First, thanks again for a great library.

I'm getting a crash in production in ParseChallengeMessage, where body[] is too short, just 3 bytes and it's crashing at `challenge.Signature = body[0:8]`

For now I've patched it up in my code (checking if challenge bytes is at least 32 long) but...

Do you think you could add "more proper" validation of `body` length in this function?

Specifically there is a branch under `NTLMSSP_NEGOTIATE_TARGET_INFO.IsSet` where the length is supposed to be at least 48, my simple application-side check doesn't cover that.

PS - no idea what the actual challenge value is or why it's like that, sorry

**Comment by vadimi** [comment]
@kmansoft so if the body is just 3 bytes it means that the Challenge message is invalid (according to the spec at least https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-nlmp/801a4681-8809-4be9-ab0d-61dcfe762786) and the result of the challenge message is needed to send it further. Any chance you can get more info? http traces with those headers would be great to see.

I can look into NTLMSSP_NEGOTIATE_TARGET_INFO parsing.

**Comment by kmansoft** [comment]
Yes the challenge must be invalid, the point is to prevent a crash.

I will look into getting the challenge string for you, but no promises, sorry, as this piece of software runs several hundred email accounts, it's haystack and needle situation.

**Comment by vadimi** [comment]
> Yes the challenge must be invalid, the point is to prevent a crash.

definitely, will also add a length check to avoid panic

**Comment by vadimi** [comment]
@kmansoft I think I figured out why you're sometimes getting a wrong challenge message. You probably see something like that:
![image](https://user-images.githubusercontent.com/1156106/116721495-5e358680-a9ab-11eb-8200-11e4a4389a47.png)

I'll have a fix for you hopefully tomorrow

**Comment by kmansoft** [comment]
Here comes the offending challenge string:

`WWW-Authenticate: Negotiate NTLM Basic realm="server name here"`

I don't think this is valid, do you? Shouldn't it be:

`WWW-Authenticate: Negotiate
WWW-Authenticate: NTLM
WWW-Authenticate: Basic realm="..."
`

**Comment by kmansoft** [comment]
You were right, this server sends this in response to challenge (sometimes):

`WWW-Authenticate: NTLM`

I can fix this on my side, sorry for the trouble.

Still, maybe validation of input data may be a good thing, just in case - production use sometimes brings surprises.

**Comment by vadimi** [comment]
alright, I've added some changes to this branch: https://github.com/vadimi/go-http-ntlm/tree/feature/retry-empty-ntlm-header

- proper trimming of NTLM challenge to detect an empty one
- I also ran into an issue when you get an empty NTLM challenge event with the right negotiate header, so I added a retry for this case

could you give it a try?

**Comment by vadimi** [comment]
will look into challenge validation a bit more

**Comment by kmansoft** [comment]
Like I said, I use my own http code so your new branch is of no use to me. Thanks though.

If you decide to add validation in challenge parsing I will be happy to pick up that change.

**Comment by vadimi** [comment]
yeah, understood, but still want to fix it in the library
