### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by lfaoro** [vadimi/go-http-ntlm#2]
Is there a way to support TLS using your package?

**Comment by vadimi** [comment]
It currently does not support that. Is it just the matter of passing `TLSClientConfig` to `http.Client`? If yes, I just added a branch [(tls)](https://github.com/vadimi/go-http-ntlm/tree/tls) that allows to pass `TLSClientConfig` to `NtlmTransport`. Please give it a try and let me know if it works for you.

**Comment by lfaoro** [comment]
works, thank you @vadimi !
