### ISSUE TITLE
Dependency on go-ntlm deprecated library

### ISSUE THREAD

**Issue by blaskovicz** [vadimi/go-http-ntlm#7]
https://github.com/vadimi/go-http-ntlm/blob/master/ntlmtransport.go#L13

`github.com/ThomsonReutersEikon/go-ntlm`

>This repository will be removed on December 14th and will no longer be maintained and ownership will also not be transferred. Please fork this repositiory if you wish to continue to use it.

**Comment by dennisbrouwer91** [comment]
Any news on this @vadimi ? Your module is broken now!

**Comment by vadimi** [comment]
let me see what I can do

**Comment by vadimi** [comment]
ok, I've forked that library awhile ago, finally switched to my fork: https://github.com/vadimi/go-http-ntlm/commit/87b04759d0c8b0cbc1d28b5eeb30a742e3eccd63 and released [v1.0.2](https://github.com/vadimi/go-http-ntlm/releases/tag/v1.0.2). I hope it resolves the issue.

**Comment by vadimi** [comment]
closing this now, please reopen if it's still an issue

**Comment by blaskovicz** [comment]
@vadimi this is now working (v1.0.3); thanks!
